name:
channels:
  - pytorch
  - dglteam
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - click=7.1.2=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - decorator=4.4.2=py_0
  - dgl-cuda10.1=0.5.1=py37_0
  - freetype=2.10.2=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - nltk=3.5=py_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - python=3.7.9=h7579374_0
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=h7b6447c_0
  - regex=2020.7.14=py37h7b6447c_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=49.6.0=py37_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py37_cu101
  - tqdm=4.48.2=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - chardet==3.0.4
    - future==0.18.2
    - idna==2.10
    - psutil==5.7.2
    - pythonds==1.2.1
    - requests==2.24.0
    - sentencepiece==0.1.91
    - stanfordcorenlp==3.9.1.1
    - torchtext==0.7.0
    - urllib3==1.25.10
prefix:

