# Users can import user customized yaml files or library provided default yaml files
includes: []
  # - $/configs/defaults.yaml
  # In the above example path, '$/' indicates the library directory which contains the config folder


preprocessing_args:
  word_emb_size: 300
  min_word_freq: 1


model_args:
  graph_construction_name: "dependency"
  graph_initialization_name: "defaults"
  graph_embedding_name: "ggnn"

  graph_construction_args:
    graph_construction_share:
      root_dir: 'examples/pytorch/text_classification/data/trec'
      topology_subdir: 'DependencyGraph'

  graph_initialization_args:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.4
    rnn_dropout: 0.1
    fix_bert_emb: false
    fix_word_emb: true
    embedding_style:
      single_token_item: true
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 1
      bert_model_name: null
      bert_lower_case: null

  graph_embedding_args:
    graph_embedding_share:
      num_layers: 1
      input_size: 300
      hidden_size: 300
      output_size: 300
      direction_option: "bi_fuse"
      feat_drop: 0.3

    graph_embedding_private:
      n_etypes: 1
      bias: true
      use_edge_weight: false

  decoder_args:
    graph_pooling_share:
      pooling_type: 'avg_pool'
      max_pool_linear_proj: false


training_args:
  batch_size: 50 # batch size
  epochs: 500 # number of maximal training epochs
  grad_clipping: 10
  early_stop_metric: 'BLEU_4'
  patience: 10
  lr: 0.001 # learning rate
  lr_patience: 2
  lr_reduce_factor: 0.5


checkpoint_args:
  out_dir: 'out/trec/ggnn_bi_fuse_dependency_ckpt'


env_args:
  seed: 1234
  gpu: 0
  no_cuda: false
