graph_construction_name: "dependency"
graph_embedding_name: "gcn"
decoder_name: "stdrnn"

out_dir: "out/cnn/gcn_bi_sep_l2_ckpt"
model_type: 'gcn'

vocab_lower_case: true

graph_construction_args:
  graph_construction_share:
    graph_name: 'dependency'
    root_dir: 'examples/pytorch/summarization/cnn'
    topology_subdir: 'DependencyGraph'
    thread_number: 4
    port: 9000
    timeout: 15000

  graph_construction_private:
    edge_strategy: 'homogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false

graph_initialization_args:
  input_size: 300
  hidden_size: 300
  word_dropout: 0.2
  rnn_dropout: 0.3
  fix_bert_emb: false
  fix_word_emb: false
  embedding_style:
    single_token_item: true
    emb_strategy: "w2v_bilstm"
    num_rnn_layers: 1
    bert_model_name: null
    bert_lower_case: null

graph_embedding_args:
  graph_embedding_share:
    num_layers: 2
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "bi_sep"
    feat_drop: 0.2

  graph_embedding_private:
    gcn_norm: 'both'
    weight: true
    bias: true
    activation: null
    allow_zero_in_degree: false
    use_edge_weight: false

decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: true
    use_coverage: true
    graph_pooling_strategy: null
    attention_type: "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3

  rnn_decoder_private:
    max_decoder_step: 100
    node_type_num: null
    tgt_emb_as_output_layer: true




# screen -S gcn_sep python -m examples.pytorch.summarization.cnn.main -g2s_config examples/pytorch/summarization/cnn/config/gcn_bisep.yaml -task_config examples/pytorch/summarization/cnn/config/lcsts.yaml