graph_construction_name: "node_emb_refined"
graph_embedding_name: "gcn"
decoder_name: "stdrnn"

graph_construction_args:
  graph_construction_share:
    graph_name: 'node_emb'
    root_dir: "examples/pytorch/semantic_parsing/graph2seq/jobs"
    topology_subdir: 'NodeEmbGraphRefined'
    thread_number: 4
    port: 9000
    timeout: 15000

  graph_construction_private:
    dynamic_init_graph_name: 'dependency'
    lower_case: true
    edge_strategy: 'homogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false
    sim_metric_type: 'weighted_cosine'
    alpha_fusion: 0.2
    num_heads: 1
    top_k_neigh: null
    epsilon_neigh: 0.5
    smoothness_ratio: 0.1
    connectivity_ratio: 0.05
    sparsity_ratio: 0.1

graph_initialization_args:
  input_size: 300
  hidden_size: 300
  word_dropout: 0.2
  rnn_dropout: 0.3
  fix_bert_emb: false
  fix_word_emb: false
  embedding_style:
    single_token_item: true
    emb_strategy: "w2v_bilstm"
    num_rnn_layers: 1
    bert_model_name: null
    bert_lower_case: null

    

graph_embedding_args:
  graph_embedding_share:
    num_layers: 3
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "bi_sep"
    feat_drop: 0.2

  graph_embedding_private:
    gcn_norm: 'both'
    weight: true
    bias: true
    activation: null
    allow_zero_in_degree: false
    use_edge_weight: true


decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: true
    use_coverage: true
    graph_pooling_strategy: null
    attention_type: "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3

  rnn_decoder_private:
    max_decoder_step: 50
    node_type_num: null
    tgt_emb_as_output_layer: true