graph_construction_name: "constituency"
graph_embedding_name: "gat"
decoder_name: "stdrnn"

graph_construction_args:
  graph_construction_share:
    graph_name: 'constituency'
    root_dir: "examples/pytorch/semantic_parsing/graph2seq/jobs"
    topology_subdir: 'ConstituencyGraph'
    thread_number: 4
    port: 9000
    timeout: 15000

  graph_construction_private:
    edge_strategy: 'homogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false

graph_initialization_args:
  input_size: 300
  hidden_size: 300
  word_dropout: 0.2
  rnn_dropout: 0.3
  fix_bert_emb: false
  fix_word_emb: false
  embedding_style:
    single_token_item: true
    emb_strategy: "w2v_bilstm"
    num_rnn_layers: 1
    bert_model_name: null
    bert_lower_case: null

graph_embedding_args:
  graph_embedding_share:
    num_layers: 3
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "bi_fuse"
    feat_drop: 0.2

  graph_embedding_private:
    heads: [2, 2, 1]
    attn_drop: 0.2
    negative_slope: 0.2
    residual: true
    activation: "relu"
    allow_zero_in_degree: true
    
decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: true
    use_coverage: true
    graph_pooling_strategy: null
    attention_type: "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3

  rnn_decoder_private:
    max_decoder_step: 50
    node_type_num: null
    tgt_emb_as_output_layer: true